# Generated by Django 5.1.1 on 2026-10-02 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Phụ đề')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Ảnh banner')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Ảnh mobile')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Link')),
                ('button_text', models.CharField(blank=True, default='Mua ngay', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('percentage', 'Phần trăm (%)'), ('fixed', 'Số tiền cố định')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá trị giảm')),
                ('minimum_order', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn hàng tối thiểu')),
                ('max_uses', models.IntegerField(default=0, verbose_name='Số lần dùng tối đa (0=không giới hạn)')),
                ('used_count', models.IntegerField(default=0, verbose_name='Số lần đã dùng')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hiệu lực từ')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Hiệu lực đến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
            },
        ),
    ]
