# Generated by Django 5.1.1 on 2026-10-02 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('uploaded', 'Đã upload biện lai'), ('confirmed', 'Đã xác nhận'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
    ]
