# Generated by Django 5.1.1 on 2026-10-02 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('province', models.CharField(max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(max_length=100, verbose_name='Phường/Xã')),
                ('street_address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tạm tính')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Phí ship')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng cộng')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='Mã giảm giá')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang đóng gói'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('shipping_method', models.CharField(choices=[('standard', 'Giao tiêu chuẩn (3-5 ngày)'), ('express', 'Giao nhanh (1-2 ngày)'), ('same_day', 'Giao hỏa tốc (trong ngày)')], default='standard', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('color_name', models.CharField(blank=True, max_length=50)),
                ('size_name', models.CharField(blank=True, max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('product_image', models.CharField(blank=True, max_length=500)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
        ),
    ]
