# Generated by Django 5.1.1 on 2026-10-02 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên màu')),
                ('hex_code', models.CharField(blank=True, max_length=7, verbose_name='Mã màu HEX')),
            ],
            options={
                'verbose_name': 'Màu sắc',
                'verbose_name_plural': 'Màu sắc',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('36', '36')], max_length=10, verbose_name='Kích thước')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kích thước',
                'verbose_name_plural': 'Kích thước',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Ảnh danh mục')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('material', models.CharField(blank=True, max_length=200, verbose_name='Chất liệu')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Hướng dẫn bảo quản')),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('unisex', 'Unisex')], default='unisex', max_length=10, verbose_name='Giới tính')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Giá gốc (VND)')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giá sale (VND)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_new_arrival', models.BooleanField(default=False, verbose_name='Hàng mới về')),
                ('is_best_seller', models.BooleanField(default=False, verbose_name='Bán chạy')),
                ('total_sold', models.IntegerField(default=0, verbose_name='Tổng đã bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('is_main', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('order', models.IntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Màu sắc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ['-is_main', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Tồn kho')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='SKU')),
                ('extra_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá thêm')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color', verbose_name='Màu sắc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Sản phẩm')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.size', verbose_name='Kích thước')),
            ],
            options={
                'verbose_name': 'Biến thể',
                'verbose_name_plural': 'Biến thể',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
